name: Deploy to S3
on:
  push:
    branches:
      - develop
      - release
      - main

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  setup-node:
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.1'

  install-dependencies:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - name: Install dependencies
        run: npm install

  install-angular-cli:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Install Angular CLI
        run: npm install -g @angular/cli

  build-project:
    runs-on: ubuntu-latest
    needs: install-angular-cli
    steps:
      - name: Build project
        run: ng build

  configure-aws-credentials:
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1  # Ajusta la región según sea necesario

  deploy-to-s3:
    runs-on: ubuntu-latest
    needs: configure-aws-credentials
    steps:
      - name: Deploy to S3
        env:
          S3_BUCKET_NAME_DEVELOP: ${{ secrets.S3_BUCKET_NAME_DEVELOP }}
          S3_BUCKET_NAME_RELEASE: ${{ secrets.S3_BUCKET_NAME_RELEASE }}
          S3_BUCKET_NAME_MAIN: ${{ secrets.S3_BUCKET_NAME_MAIN }}
        run: |
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            aws s3 sync ./dist/app-angular/browser/ s3://${{ env.S3_BUCKET_NAME_DEVELOP }} --delete
          elif [[ "${GITHUB_REF##*/}" == "release" ]]; then
            aws s3 sync ./dist/app-angular/browser/ s3://${{ env.S3_BUCKET_NAME_RELEASE }} --delete
          elif [[ "${GITHUB_REF##*/}" == "main" ]]; then
            aws s3 sync ./dist/app-angular/browser/ s3://${{ env.S3_BUCKET_NAME_MAIN }} --delete
