# name: Deploy to S3

# on:
#   push:
#     branches:
#       - develop
#       - release
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '18.19.1' 

#     - name: Install dependencies
#       run: npm install

#     - name: Install Angular CLI
#       run: npm install -g @angular/cli

#     - name: Build project
#       run: ng build

#     - name: Deploy to S3 (develop)
#       if: github.ref == 'refs/heads/develop'
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
#         AWS_REGION: us-east-1 
#         S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_DEVELOP }}
 
#       run: aws s3 sync ./dist/app-angular s3://$S3_BUCKET_NAME --delete

#     - name: Deploy to S3 (release)
#       if: github.ref == 'refs/heads/release'
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
#         AWS_REGION: us-east-1
#         S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_RELEASE }}
  
#       run: aws s3 sync ./dist/app-angular s3://$S3_BUCKET_NAME --delete

#     - name: Deploy to S3 (main)
#       if: github.ref == 'refs/heads/main'
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS-SESSION-TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} 
#         AWS_REGION: us-east-1
#         S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_MAIN }}
  
#       run: aws s3 sync ./dist/app-angular s3://main-angular-devops --delete