name: Deploy to S3

on:
  push:
    branches:
      - develop
      - release
      - main

jobs:

  # Checkout Code (independent step)
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  # Setup Node.js (independent step)
  setup-nodejs:
    runs-on: ubuntu-latest
    needs: checkout-code  # This step depends on checkout-code being finished
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.1'

  # Build and Deploy (branch-dependent steps)
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [checkout-code, setup-nodejs]  # This step depends on both previous steps
    steps:
      - name: Install dependencies
        run: npm install
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Build project
        run: ng build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1  # Adjust the region as needed

      - name: Deploy to S3 (develop branch)
        if: ${{ github.ref == 'refs/heads/develop' }}
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_DEVELOP }}
        run: aws s3 sync ./dist/app-angular/browser/ s3://${{ env.S3_BUCKET_NAME }} --delete

      - name: Deploy to S3 (release branch)
        if: ${{ github.ref == 'refs/heads/release' }}
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_RELEASE }}
        run: aws s3 sync ./dist/app-angular/browser/ s3://${{ env.S3_BUCKET_NAME }} --delete

      - name: Deploy to S3 (main branch)
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_MAIN }}
        run: aws s3 sync ./dist/app-angular/browser/ s3://${{ env.S3_BUCKET_NAME }} --delete
