name: Deploy to S3

on:
  push:
    branches:
      - develop
      - release
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [develop, release, main]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.19.1' 

    - name: Install dependencies
      run: npm install

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Build project
      run: ng build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
        aws-region: us-east-1  

    - name: Deploy to S3
      env:
        S3_BUCKET_NAME_DEVELOP: ${{ secrets.S3_BUCKET_NAME_DEVELOP }}
        S3_BUCKET_NAME_RELEASE: ${{ secrets.S3_BUCKET_NAME_RELEASE }}
        S3_BUCKET_NAME_MAIN: ${{ secrets.S3_BUCKET_NAME_MAIN }}
      run: |
        if [ "${{ matrix.branch }}" == "develop" ]; then
          BUCKET_NAME=${{ env.S3_BUCKET_NAME_DEVELOP }}
        elif [ "${{ matrix.branch }}" == "release" ]; then
          BUCKET_NAME=${{ env.S3_BUCKET_NAME_RELEASE }}
        elif [ "${{ matrix.branch }}" == "main" ]; then
          BUCKET_NAME=${{ env.S3_BUCKET_NAME_MAIN }}
        fi
        aws s3 sync ./dist/app-angular/browser/ s3://$BUCKET_NAME --delete